### ISSUE TITLE
Implement create-functionality for workout routines in frontend

### ISSUE THREAD

**Issue by Pankai222** [Pankai222/show-me-the-way-arnold#9]
Index page needs a button which can toggle a form for creating a new workout routine. 

The form can have input fields for name, duration, difficulty, etc. + a dropdown for exercises. 

Exercises can be retrieved through the GetExercises-endpoint. A service in frontend for the endpoint has to be added first

**Comment by nullxDEADBEEF** [comment]
Has been implemented :^)
